### PR TITLE
Reindent and add Python 2/3 compatability

### PR DESCRIPTION
**Pull request by dhimmel**
Untested.

### CODE REVIEW

**Comment by cgreene** [comment]
Testing now by reformatting adipose_tissue.dab to a .pcl

**Comment by kkloste** [comment]
@dhimmel To answer your [question in /greenelab/PAINT-prelim](https://github.com/greenelab/PAINT-prelim/pull/5#issuecomment-249677906), the errors came up using that repo;
I've since followed your instructions, pulled from here, and it's running correctly now.

Still seems to be slow, though... (using very little RAM, as it was before).

**Comment by cgreene** [comment]
@kkloste : also running tests under python2 and python3 and it's slow here too. Dat2Dab may be the answer:
http://libsleipnir.bitbucket.org/index.html#sec_building

Ubuntu w/ mercurial is usually pretty easy to install.

**Comment by cgreene** [comment]
Merging this so that we can get it transferred over to:
http://github.com/functionlab/flib which is where it should reside permanently.

**Comment by kkloste** [comment]
I'm trying to get sleipnir installed as per the link you sent me, @cgreene  -- unfortunately, I'm on a fedora machine.
mercurial was still easy enough to install, but the rest is not working quite as easily.
Might take me a bit to get through this.

**Comment by cgreene** [comment]
@kkloste : Still running for me this morning. This seems surprisingly slow. I'll see if I can profile on a smaller file to figure out what's up.

**Comment by cgreene** [comment]
@kkloste : the previous version runs successfully under 2.7 at a reasonable speed. It looks like under python3 there's an issue in `open_file`.

**Comment by dhimmel** [comment]
Given that we have a while loop, my guess is [this is the problematic line](https://github.com/FunctionLab/flib/blob/795d3255f898c52d826e286e560788055f4345ac/dat.py#L36):

``` python
dab_file.read(2) == '\0\0'
```

Confirming that in Python 2, `b'\0\0' == '\0\0'` is True, while in 3 it's False.

**Comment by cgreene** [comment]
Yep - have a fixed version incoming.

**Pull request merged**
